# Force a Python-only build and ensure Python is installed for the provider.
providers = ["python"]

[phases.setup]
# Install Python + system deps needed by your app
nixPkgs = [
  "python312",
  "chromium",
  "tesseract",
  "poppler_utils"
]

# DO NOT override the provider's install phase.
# The Python provider will:
#   - run: python -m venv --copies /opt/venv
#   - run: . /opt/venv/bin/activate && pip install -r requirements.txt

[phases.build]
# AFTER python:install created /opt/venv and installed requirements
cmds = [
  "/opt/venv/bin/python -m pip install --upgrade pip",
  "/opt/venv/bin/python -m pip install playwright",
  "/opt/venv/bin/playwright install --with-deps chromium"
]

[start]
cmd = "uvicorn app_v2_clean:app --host 0.0.0.0 --port ${PORT:-8000}"

[variables]
NIXPACKS_PYTHON_VERSION = "3.12"
NIXPACKS_PYTHON_PACKAGE_MANAGER = "requirements"
