# Force the Python provider to run alongside anything auto-detected (like Node)
providers = ["...", "python"]

[phases.setup]
# Keep system packages you need
# Use "..." to preserve whatever Nixpacks would normally add
nixPkgs = ["...", "chromium", "tesseract", "poppler_utils"]

[phases.install]
# EXTEND the provider's default install step instead of replacing it.
# The "..." placeholder runs the default (pip install -r requirements.txt) first,
# then we run Playwright setup.
cmds = [
  "...",
  "python3 -m pip install playwright",
  "playwright install --with-deps chromium"
]

[start]
# Start the ASGI server bound to Railway's $PORT
cmd = "uvicorn app_v2_clean:app --host 0.0.0.0 --port ${PORT:-8000}"

[variables]
# Make sure the provider chooses Python 3.12 and uses requirements.txt
NIXPACKS_PYTHON_VERSION = "3.12"
NIXPACKS_PYTHON_PACKAGE_MANAGER = "requirements"
