providers = ["python"]

[phases.setup]
# Python + system tools (Chromium from Nix, no apt)
nixPkgs = ["python312", "chromium", "tesseract", "poppler_utils"]

[phases.build]
# Install only the Python package, no browser download.
# Also ensure /usr/bin/chromium points to the Nix chromium path.
cmds = [
  "/opt/venv/bin/python -m pip install --upgrade pip",
  "/opt/venv/bin/python -m pip install playwright",
  "ln -sf $(which chromium) /usr/bin/chromium || true"
]

[start]
# Prefer uvicorn so it binds to $PORT
cmd = "uvicorn app_v2_clean:app --host 0.0.0.0 --port ${PORT:-8000}"

[variables]
# Tell Playwright to skip downloading browsers and use system Chromium
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
PW_CHROMIUM_BIN = "/usr/bin/chromium"
NIXPACKS_PYTHON_VERSION = "3.12"
NIXPACKS_PYTHON_PACKAGE_MANAGER = "requirements"


[variables]
NIXPACKS_PYTHON_VERSION = "3.12"
NIXPACKS_PYTHON_PACKAGE_MANAGER = "requirements"
