[phases.setup]
nixPkgs = ['python312', 'chromium', 'tesseract', 'poppler_utils']

[phases.install]
cmds = [
  'python3 -m pip install --upgrade pip',
  'python3 -m pip install -r requirements.txt',
  'python3 -m pip install playwright',
  'playwright install --with-deps chromium'
]

[start]
cmd = 'uvicorn app_v2_clean:app --host 0.0.0.0 --port ${PORT:-8000}'

[variables]
NIXPACKS_PYTHON_VERSION = '3.12'
NIXPACKS_PYTHON_PACKAGE_MANAGER = 'requirements'
